name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the deployable artifact files
        required: true
        type: string
    outputs:
      result:
        description: The status of the deploy job
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step_result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls -lh
      - name: Output information
        run: echo "Deploying & uploading"
      - name: Set result output
        id: set-result
        run: echo "step_result=success" >> $GITHUB_OUTPUT
